---
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: binxio
      name: homebrew-cru
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: 'https://github.com/binxio/cru'
    description: 'utility to update container image references'
    folder: formula
    commit_author:
      name: Mark van Holsteijn
      email: mark.van.holsteijn@gmail.com
    install: |-
      bin.install "cru"
    test: |
      system "#{bin}/cru --help"
