steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: '/bin/bash'
    args:
      - -c
      - 'docker build -t gcr.io/$PROJECT_ID/cru:$SHORT_SHA . &&
         docker push gcr.io/$PROJECT_ID/cru:$SHORT_SHA '
  - name: gcr.io/cloud-builders/docker
    entrypoint: '/bin/bash'
    args:
      - -c
      - 'docker build -t gcr.io/$PROJECT_ID/cru:${TAG_NAME:-latest} . &&
         docker push gcr.io/$PROJECT_ID/cru:${TAG_NAME:-latest}'
    env:
      - TAG_NAME=$TAG_NAME
